# Pandas Quick Review

## 00. 라이브러리 불러오기 & 데이터 업로드

In [0]:
import pandas as pd

In [0]:
url = 'https://raw.githubusercontent.com/RayleighKim/Example_datasets/master/Graduate_apply.csv'

In [3]:
pd.read_csv(url)

     admit  gre   gpa  rank
0        0  380  3.61     3
1        1  660  3.67     3
2        1  800  4.00     1
3        1  640  3.19     4
4        0  520  2.93     4
..     ...  ...   ...   ...
395      0  620  4.00     2
396      0  560  3.04     3
397      0  460  2.63     2
398      0  700  3.65     2
399      0  600  3.89     3

[400 rows x 4 columns]

## 01. Creating Data Frames

In [0]:
import pandas as pd

In [6]:
# Dataframes 생성
d = {
   'col1': ['Item0', 'Item0', 'Item1', 'Item1'],
   'col2': ['Gold', 'Bronze', 'Gold', 'Silver'],
   'col3': [1, 2, 3, 4]
}
df = pd.DataFrame(d)
df

    col1    col2  col3
0  Item0    Gold     1
1  Item0  Bronze     2
2  Item1    Gold     3
3  Item1  Silver     4

In [0]:
from sklearn.datasets import load_boston
boston = load_boston()

In [10]:
type(boston.data)

numpy.ndarray

In [14]:
pd.DataFrame(boston.data, columns=boston.feature_names)

        CRIM    ZN  INDUS  CHAS    NOX  ...  RAD    TAX  PTRATIO       B  LSTAT
0    0.00632  18.0   2.31   0.0  0.538  ...  1.0  296.0     15.3  396.90   4.98
1    0.02731   0.0   7.07   0.0  0.469  ...  2.0  242.0     17.8  396.90   9.14
2    0.02729   0.0   7.07   0.0  0.469  ...  2.0  242.0     17.8  392.83   4.03
3    0.03237   0.0   2.18   0.0  0.458  ...  3.0  222.0     18.7  394.63   2.94
4    0.06905   0.0   2.18   0.0  0.458  ...  3.0  222.0     18.7  396.90   5.33
..       ...   ...    ...   ...    ...  ...  ...    ...      ...     ...    ...
501  0.06263   0.0  11.93   0.0  0.573  ...  1.0  273.0     21.0  391.99   9.67
502  0.04527   0.0  11.93   0.0  0.573  ...  1.0  273.0     21.0  396.90   9.08
503  0.06076   0.0  11.93   0.0  0.573  ...  1.0  273.0     21.0  396.90   5.64
504  0.10959   0.0  11.93   0.0  0.573  ...  1.0  273.0     21.0  393.45   6.48
505  0.04741   0.0  11.93   0.0  0.573  ...  1.0  273.0     21.0  396.90   7.88

[506 rows x 13 columns]

In [15]:
# Numpy Array => Pandas DataFrame
import numpy as np

dates = pd.date_range('20171201', periods=6)
# DatetimeIndex(['2017-12-01', '2017-12-02', '2017-12-03', '2017-12-04',
#                '2017-12-05', '2017-12-06'],
#               dtype='datetime64[ns]', freq='D')

df = pd.DataFrame(np.random.randn(6, 4), index=dates, columns=list('ABCD'))
#                   A         B         C         D
# 2013-01-01  0.469112 -0.282863 -1.509059 -1.135632
# 2013-01-02  1.212112 -0.173215  0.119209 -1.044236
# 2013-01-03 -0.861849 -2.104569 -0.494929  1.071804
# 2013-01-04  0.721555 -0.706771 -1.039575  0.271860
# 2013-01-05 -0.424972  0.567020  0.276232 -1.087401
# 2013-01-06 -0.673690  0.113648 -1.478427  0.524988

df

                   A         B         C         D
2017-12-01  1.420674 -1.854278  0.593907  0.011855
2017-12-02 -1.404431 -0.098931 -1.432124 -0.761741
2017-12-03  0.978222  0.160127 -1.942861 -1.089619
2017-12-04  0.007631 -0.120050 -1.440324 -0.298092
2017-12-05  1.242949 -0.727970 -1.650348 -0.617298
2017-12-06 -0.898894  0.793329  0.354446 -1.269095

In [16]:
# Pandas DataFrame => Numpy Array
np_array = df.values
print(np_array, np_array.shape)

[[ 1.42067407 -1.85427809  0.59390664  0.01185493]
 [-1.40443147 -0.09893134 -1.43212367 -0.7617408 ]
 [ 0.97822186  0.16012665 -1.9428612  -1.08961948]
 [ 0.00763103 -0.12004962 -1.44032351 -0.2980921 ]
 [ 1.24294906 -0.72796953 -1.65034767 -0.61729827]
 [-0.89889354  0.79332853  0.354446   -1.26909484]] (6, 4)

In [0]:
# to_csv
df.to_csv('./file.csv', header=True, index=False, encoding='utf-8')

In [18]:
ls

file.csv  sample_data/

## 02. Previewing Data

In [19]:
# 첫 5개 행의 데이터를 보여줍니다.
df.head()

                   A         B         C         D
2017-12-01  1.420674 -1.854278  0.593907  0.011855
2017-12-02 -1.404431 -0.098931 -1.432124 -0.761741
2017-12-03  0.978222  0.160127 -1.942861 -1.089619
2017-12-04  0.007631 -0.120050 -1.440324 -0.298092
2017-12-05  1.242949 -0.727970 -1.650348 -0.617298

In [20]:
# 마지막 3개 행의 데이터를 보여줍니다.
df.tail(3)

                   A         B         C         D
2017-12-04  0.007631 -0.120050 -1.440324 -0.298092
2017-12-05  1.242949 -0.727970 -1.650348 -0.617298
2017-12-06 -0.898894  0.793329  0.354446 -1.269095

In [23]:
# 데이터 프레임 모양 확인 - (rows, cols) tuple
df.shape

(6, 4)

In [24]:
# 칼럼명 출력
print(df.columns)
print(list(df))

Index(['A', 'B', 'C', 'D'], dtype='object')
['A', 'B', 'C', 'D']

In [25]:
# 각 칼럼의 데이터 타입
df.dtypes

A    float64
B    float64
C    float64
D    float64
dtype: object

In [26]:
# 데이터 출력 - numpy array
df.values

array([[ 1.42067407, -1.85427809,  0.59390664,  0.01185493],
       [-1.40443147, -0.09893134, -1.43212367, -0.7617408 ],
       [ 0.97822186,  0.16012665, -1.9428612 , -1.08961948],
       [ 0.00763103, -0.12004962, -1.44032351, -0.2980921 ],
       [ 1.24294906, -0.72796953, -1.65034767, -0.61729827],
       [-0.89889354,  0.79332853,  0.354446  , -1.26909484]])

In [27]:
# 간단한 통계 정보
df.describe()

              A         B         C         D
count  6.000000  6.000000  6.000000  6.000000
mean   0.224358 -0.307962 -0.919551 -0.670665
std    1.183100  0.903156  1.098070  0.479464
min   -1.404431 -1.854278 -1.942861 -1.269095
25%   -0.672262 -0.575990 -1.597842 -1.007650
50%    0.492926 -0.109490 -1.436224 -0.689520
75%    1.176767  0.095362 -0.092196 -0.377894
max    1.420674  0.793329  0.593907  0.011855

## 03. Sorting

In [0]:
df = pd.read_csv(url)

In [0]:
# index로 정렬
df.sort_index(axis=0, ascending=False).head()

In [0]:
# 특정 컬럼의 값으로 정렬
df.sort_values(by=['admit', 'gpa'], ascending=False).head()

### 실습

In [0]:
# pandas 라이브러리 호출

# pandas read_csv 함수를 이용하여 graduate_apply.csv 파일을 읽고, data_frame 변수에 담습니다. 

# data_frame의 shape를 확인합니다.

# data_frame의 칼럼명과 각 칼럼의 데이터 타입을 확인합니다.

# data_frame의 데이터의 첫 3행의 데이터와 마지막 3행의 데이터를 출력합니다.

# data_frame의 데이터를 numpy array로 변환하여 출력합니다.

# data_frame의 데이터를 'gra' 칼럼을 기준으로 오름차순으로 정렬합니다.

## 04. Selecting/Querying

In [0]:
df
df = pd.read_csv(url)
df.columns = ['admit', 'gre', 'gpa', 'rank']

In [51]:
# 칼럼명으로 조회 1
df.gre.head() # 매우 주의

0    380
1    660
2    800
3    640
4    520
Name: gre, dtype: int64

In [52]:
# 칼럼명으로 조회 2
df['gre'].head()
df['gre'].unique()          # 중복 제거

array([380, 660, 800, 640, 520, 760, 560, 400, 540, 700, 440, 480, 780,
       360, 500, 600, 680, 620, 580, 460, 740, 300, 720, 340, 420, 220])

In [53]:
# 두 개의 칼럼 동시 조회
df[['gpa', 'gre']].head()

    gpa  gre
0  3.61  380
1  3.67  660
2  4.00  800
3  3.19  640
4  2.93  520

In [54]:
# 행번호 1 조회
df.iloc[1]

admit      1.00
gre      660.00
gpa        3.67
rank       3.00
Name: 1, dtype: float64

In [55]:
# 행번호 1~3 조회
df.iloc[1:3]

   admit  gre   gpa  rank
1      1  660  3.67     3
2      1  800  4.00     1

In [56]:
# 0번째 row, 0번째 column
df.iloc[0, 0]

0

In [57]:
# 0~4 rows & 0~2 columns
df.iloc[0:4, 0:2]

   admit  gre
0      0  380
1      1  660
2      1  800
3      1  640

In [0]:
# Produces and array, not a single value!
# (df.gpa > 3.5).head() # 매우 주의

In [0]:
# Query by a single column value
# df[df.gpa > 3.0].head() # 매우 주의

In [60]:
df.loc[df['rank']==1]

     admit  gre   gpa  rank
2        1  800  4.00     1
6        1  560  2.98     1
11       0  440  3.22     1
12       1  760  4.00     1
14       1  700  4.00     1
..     ...  ...   ...   ...
368      0  580  4.00     1
372      1  680  2.42     1
373      1  620  3.37     1
383      0  660  4.00     1
385      0  420  3.02     1

[61 rows x 4 columns]

In [47]:
df.columns

Index(['admit', 'gre', 'gpa', 'rank'], dtype='object')

In [0]:
# Query by a single column, if it is in a list of predefined values
df[df['rank'].isin([1, 2])].head()

In [0]:
# A conjunction query using two columns
df[(df['gpa'] > 3.0) & (df['rank'] == 3)].head()

In [0]:
# A disjunction query using two columns
df[(df['gpa'] > 3.0) | (df['rank'] == 3)].head()

In [0]:
# Dataframes 생성
d = {
   'col1': ['Item0', 'Item0', 'Item1', 'Item1'],
   'col2': ['Gold', 'Bronze', 'Gold', 'Silver'],
   'col3': [1, 2, 3, 4]
}
df1 = pd.DataFrame(d)

# 문자열이 들어있는 row만 조회
df1[df1.col2.str.contains('ilver')]

### 실습

In [0]:
# pandas 라이브러리 호출

# pandas read_csv 함수를 이용하여 graduate_apply.csv 파일을 읽고, data_frame 변수에 담습니다. 

# data_frame의 shape를 확인합니다.

# data_frame의 칼럼명과 각 칼럼의 데이터 타입을 확인합니다.

# data_frame의 데이터의 첫 3행의 데이터와 마지막 3행의 데이터를 출력합니다.

# 'gpa' 칼럼의 데이터를 조회합니다. 

# unique 함수를 가지고 'rank'의 칼럼에 들어있는 데이터의 종류를 확인합니다.

# 100번째 행의 데이터를 조회합니다.

# rank가 0인 데이터를 조회합니다. 

# rank가 3, 4인 데이터의 갯수를 확인합니다.

## 05. Modifying Data Frames

In [48]:
df.head()

               admit       gre       gpa      rank
2017-12-01  1.420674 -1.854278  0.593907  0.011855
2017-12-02 -1.404431 -0.098931 -1.432124 -0.761741
2017-12-03  0.978222  0.160127 -1.942861 -1.089619
2017-12-04  0.007631 -0.120050 -1.440324 -0.298092
2017-12-05  1.242949 -0.727970 -1.650348 -0.617298

In [49]:
df['total_score'] = df['gre'] + df['gpa']*200
df.head()

               admit       gre       gpa      rank  total_score
2017-12-01  1.420674 -1.854278  0.593907  0.011855   116.927050
2017-12-02 -1.404431 -0.098931 -1.432124 -0.761741  -286.523665
2017-12-03  0.978222  0.160127 -1.942861 -1.089619  -388.412114
2017-12-04  0.007631 -0.120050 -1.440324 -0.298092  -288.184751
2017-12-05  1.242949 -0.727970 -1.650348 -0.617298  -330.797503

In [0]:
# 인덱스와 칼럼명으로 조회 & 수정
df1.loc[1, 'col2'] = 'Bronze and Gold' 
df1

In [0]:
# 행번호, 열번호로 조회 & 수정
df1.iloc[1, 1] = 'Bronze again' 
df1

In [0]:
# Replaces the column with the array. It could be a numpy array or a simple list.
# Could also be used to create new columns
df1.loc[1:3, 'col3'] = ['Unknown0'] * 3
df1

In [0]:
# Equivalent to the previous
df1.col3 = ['Unknown1'] * len(df1) 
df1

# 위와 동일하게 동작하는 코드
# df1.loc[:, 'col3'] = ['Unknown2'] * len(df1)

In [0]:
def f(x):
    return x + ' New Column';

# Uses the unary function f to create a new column based on an existing one
df1.col4 = f(df1.col3) 
df1

In [0]:
def g(x, y):
    return x + '_' + y

# Uses the 2-arg function g to create a new column based on 2 existing columns
df1.col4 = g(df1.col3, df1.col2)
df1

In [0]:
# df = pd.read_csv('./Graduate_apply.csv', sep=',', skipinitialspace=True, engine='python')
print(df.head())
print("------")

# 특정 칼럼의 Dummy Variable을 얻기
df_rank = pd.get_dummies(df['rank'])
print(df_rank.head())
print("------")

# Dummy 데이터를 원래 데이터와 합치기
df_new = pd.concat([df, df_rank], axis=1)
print(df_new.head())
print("------")

# 특정 칼럼 제거하기
df_new.drop('rank', axis=1, inplace=True)
print(df_new.head())
print("------")

# 여러 칼럼 동시 제거하기
df_new.drop(['gre', 'gpa'], axis=1, inplace=True)
print(df_new.head())
print("------")

In [0]:
pd.get_dummies(df, columns=['rank'])

## 06. Group by, Join, Rolling

In [0]:
import pandas as pd

In [0]:
df = pd.read_csv('https://raw.githubusercontent.com/RayleighKim/Example_datasets/master/Graduate_apply.csv')

In [0]:
print(df.shape)
df.head(3)

[고군분투의 흔적](https://www.facebook.com/photo.php?fbid=1939114629501924&set=a.1046527102094019&type=3)

### 06-1. Group by

일단 단순한 수준에서 겪어보자

In [0]:
df.groupby(by=['rank'], as_index = False)['gre'].mean()

In [0]:
df.groupby(by = ['rank', 'admit'], as_index=False)['gre', 'gpa'].mean()

In [0]:
df.groupby(by = ['rank', 'admit'], as_index=False)['gre', 'gpa'].std()

In [0]:
df.groupby(by = ['rank', 'admit'], as_index=False).count()

In [0]:
df.groupby(by = ['rank', 'admit'], as_index=False)['gre'].count()

이름들이 조금 이상하다. 컬럼이름을 바꾸어보자

In [0]:
df_by_rank = df.groupby(by = ['rank'], as_index=False)['gre'].mean()
df_by_rank.head()

In [0]:
if 'gre' in df_by_rank.columns :
    df_by_rank.rename(columns={'gre':'gre_mean'}, inplace = True)

In [0]:
df_by_rank.head()

실습해봅시다!

rank, admit 기준으로 gre의 최대값을 출력하시오.

.max()를 사용하면 됩니다.

In [0]:
## Your Code

### 06-2 Join

In [0]:
mean_by_rank = df.groupby(by = ['rank'], as_index=False)['gre', 'gpa'].mean()
mean_by_rank.rename(columns = {'gre':'gre_mean', 'gpa':'gpa_mean'}, inplace = True)
mean_by_rank

In [0]:
'''
pandas,  ver0.22.0 기준으로 망가져 있는 기능.
rank가 미쳐보이지만 놀랍게도, 값들은 정상입니다.
'''
std_by_rank = df.groupby(by = ['rank'], as_index=False)['gre', 'gpa'].std()
std_by_rank.rename(columns = {'gre':'gre_std', 'gpa':'gpa_std'}, inplace = True)
std_by_rank

pandas ver0.22.0 기준으로 망가져 있는 기능을 우회하여 사용하는 가장 빠른 방법은 다음과 같습니다.

In [0]:
std_by_rank['rank'] = mean_by_rank['rank']
std_by_rank

판다스에서 join은 굉장히 간단합니다.

자동으로 key를 잡아줍니다!

다만, 자동으로 inner join을 합니다.

In [0]:
pd.merge(mean_by_rank, std_by_rank)

In [0]:
pd.merge(mean_by_rank, std_by_rank, on = 'rank', how = 'outer')

multiple key에 대해서도 자동으로 join이 됩니다!

In [0]:
mean_by_rank2 = df.groupby(by = ['rank', 'admit'], as_index=False)['gre', 'gpa'].mean()
mean_by_rank2.rename(columns = {'gre':'gre_mean', 'gpa':'gpa_mean'}, inplace = True)
mean_by_rank2

In [0]:
std_by_rank2 = df.groupby(by = ['rank','admit'], as_index=False)['gre', 'gpa'].std()
std_by_rank2.rename(columns = {'gre':'gre_std', 'gpa':'gpa_std'}, inplace = True)
std_by_rank2['rank'] = mean_by_rank2['rank']
std_by_rank2

In [0]:
pd.merge(mean_by_rank2,std_by_rank2)

실습해봅시다!

rank, admit 기준으로 gre의 최소값을 담는 dataframe을 만들어

다음의 데이터 프레임(df_to_merge)와 join 하시오.

In [0]:
df_to_merge = pd.merge(mean_by_rank2, std_by_rank2)
df_to_merge.head()

In [0]:
df_mingre = df.groupby(by = ['rank','admit'], as_index=False)['gre'].min()
df_mingre

In [0]:
### Your Code here

### 06-3 Rolling

In [0]:
import pandas as pd

In [0]:
stock = pd.read_csv('https://raw.githubusercontent.com/RayleighKim/Example_datasets/master/Stock_Edwards_Lifesciences_corporation.csv')
stock.head()

Date 와 Close 가격만을 남겨 보죠.

In [0]:
stock = stock[['Date', 'Close']]
stock.head()

기준일 포함하여 과거 3일의 평균을 데이터 프레임에 붙여봅시다.

In [0]:
stock['Close_MA_3'] = stock['Close'].rolling(3).mean()
stock.head(10)

min_periods를 기억하자

In [0]:
stock['Close_MA_3(2)'] = stock['Close'].rolling(3, min_periods=1).mean()
stock.head(10)

기준일 포함하여 과거 3일 중 최대값은 어떨까요?

In [0]:
stock['Close_MM_3'] = stock['Close'].rolling(3).max()
stock.head(10)

기준일을 포함하지 않은, 과거 3일의 평균을 붙인다면?

In [0]:
stock['Close_MA_3_lag1'] = stock['Close_MA_3'].shift()
stock.head()

실습!!

stock 옆에, 과거 4일의 표준편차를 붙이시오!

In [0]:
stock['Close_MS_3'] = ## Your Code
    
stock.head()